### ISSUE TITLE
contact / websocket api

### ISSUE THREAD

**Issue by ril3y** [timdorr/model-s-api#67]
Hi Tim,

Sorry if this is not the place for this type of question.  Do you have a place where we can chat / maillist etc?  Also I have a model 3 and pretty much everything you have done with the s api works for me.  Minus the sunroom since it does not have one :)

**Websocket stuff.**
I didnt see any documentation but do you know anything about getting notifications.  Say when you unplug your charger and in the app you get messages saying its unplugged?  Is this communication documented?  

**API Sniffing.**
I used to use a packet capture app to sniff ssl enabled communications but its no longer working (I suspect cert pinning?) How are you inspecting the apis from the app?  Or are you decompiling it?

Thanks for the help and if you need any model 3 specific tests let me know.

Riley

**Comment by timdorr** [comment]
The push notifications are done via APN (for iOS) and GCM/FCM (for Android). Those are direct-to-device, so there's no API to control per se. You may be able to set up a dummy device and request that Tesla send notifications to it, but I'm not sure how that works, so you're on your own.

I decompile the Android app, since it's now written in React Native. There is a file describing the entire API surface, which is convenient. You are right there is cert pinning on the apps now, but you can get around that on Android with some Magisk or Xposed modules.
